#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    intakePot,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

intrinsic void myFunc(compileConst int num) asm(opcdCallSub, variableCompileConstByte(num));

void testFunc();

//#define BCI_SEM_DEBUG_FULL
//#include "BCI\BCI.h"

//#include "uartHandler.c"
//#include "motorControl.c"
//#include "decisionHandler.c"

void testFunc() {}

task main()
{
	//initUART();

	//Start reading from pi
	//startTask(readBuffer);

	//Let robot drive itself
	//startTask(commandRobot);

	while (true)
	{
		//Send data to pi
		//sendSTDMsg();

		testFunc();
		myFunc(1);

		//Task wait
		wait1Msec(15);
	}
}
