#pragma config(UART_Usage, UART1, uartUserControl, baudRate9600, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    intakePot,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Bulldog_Core_Includes.h"

#define MSG_LENGTH 10
short msg[MSG_LENGTH];

task main()
{
	short msgCount = 0;

	setBaudRate(UART1, baudRate9600);

	while (true)
	{
		//Send start byte
		sendChar(UART1, 0xFA);

		//Send msg header
		sendChar(UART1, msgCount++);

		//Send analog data
		sendChar(UART1, (short)SensorValue[intakePot]);

		//Send digital data
		sendChar(UART1, (short)SensorValue[leftQuad]);
		sendChar(UART1, (short)SensorValue[rightQuad]);

		//Task wait
		wait1Msec(15);
	}
}

task readBuffer()
{
	unsigned int index = 0;

	while (true)
	{
		//Start byte
		if ((msg[index] = getChar(UART1)) == 0xFA)
		{
			for (index = 1; index < MSG_LENGTH; index++)
			{
				if ((msg[index] = getChar(UART1)) == 0xFF)
				{
					index--;
				}
			}
			index = 0;
		}

		//Task wait
		wait1Msec(1);
	}
}

void setLeftMotors(int powerValue){
	motor[leftMotor] = powerValue;
}

void setRightMotors(int powerValue){
	motor[rightMotor] = powerValue;
}

bool driveStraight(int distance){
	long encoderLeft = SensorValue[leftQuad], encoderRight = SensorValue[rightQuad];
	pos_PID distancePID , anglePID;
	float distanceElapsed = 0;
	pos_PID_InitController(&distancePID, &distanceElapsed, 0, 0, 0);
	float angleChange = 0;
	pos_PID_InitController(&anglePID, &angleChange, 0, 0, 0);
	int targetDistance = distance;
	pos_PID_SetTargetPosition(&distancePID, targetDistance);
	pos_PID_SetTargetPosition(&anglePID, 0);
	bool atTarget = false;
	long currentLeft, currentRight;
	int distOutput, angleOutput;
	while (!atTarget){
		currentLeft = (SensorValue[leftQuad] - encoderLeft);
		currentRight = (SensorValue[rightQuad] - encoderRight);
		distanceElapsed = (currentLeft + currentRight) / 2.0;
		angleChange = currentRight - currentLeft
		distOutput = pos_PID_StepController(&distancePID);
		angleOutput = pos_PID_StepController(&anglePID);
		setLeftMotors(distOutput + angleOutput);
		setRightMotors(distOutput - angleOutput);
	}
}














