#pragma config(UART_Usage, UART1, uartUserControl, baudRate9600, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    intakePot,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	short msgCount = 0;

	setBaudRate(UART1, baudRate9600);

	while (true)
	{
		//Send start byte
		sendChar(UART1, 0xFA);

		//Send msg header
		sendChar(UART1, msgCount++);

		//Send analog data
		sendChar(UART1, (short)SensorValue[intakePot]);

		//Send digital data
		sendChar(UART1, (short)SensorValue[leftQuad]);
		sendChar(UART1, (short)SensorValue[rightQuad]);

		//Task wait
		wait1Msec(15);
	}
}
